--- # Master playbook
- hosts: apacheweb
  user: henry
  become: yes
  connection: ssh
  gather_facts: yes
  pre_tasks:
  - name: Start time
    raw: date > /home/henry/log/time.log
  roles: 
  - { role: redhat_webservers, when: "ansible_os_family == 'RedHat'" }
  - { role: debian_webservers, when: "ansible_os_family == 'Debian'" }
  post_tasks:
  - name: Start time
    raw: date >> /home/henry/log/time.log

